[package]
name = "xtask"
description = "RasterSong developer tasks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
lzma-rs = "0.3"
sha2 = "0.10"
tar = "0.4"
zip = { version = "2", default-features = false, features = ["deflate"] }

[lints]
workspace = true
