// Shared by several test binaries, each of which uses only some of these helpers.
#![allow(dead_code)]

use std::hash::{DefaultHasher, Hash, Hasher};
use std::path::PathBuf;

use rastersong_media::{FfmpegBackend, MediaBackend, VideoSource};

/// Path to a fixture generated by `cargo xtask fixtures`.
pub fn fixture(name: &str) -> PathBuf {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures")
        .join(name);
    assert!(
        path.exists(),
        "missing fixture {}; run `cargo xtask fixtures`",
        path.display()
    );
    path
}

pub fn backend() -> FfmpegBackend {
    FfmpegBackend::new().unwrap()
}

pub fn open(name: &str) -> Box<dyn VideoSource> {
    backend().open_video(&fixture(name)).unwrap()
}

pub fn hash(data: &[u8]) -> u64 {
    let mut hasher = DefaultHasher::new();
    data.hash(&mut hasher);
    hasher.finish()
}

/// A deterministic shuffle of `0..n` (xorshift + Fisher-Yates), so failures are reproducible.
pub fn shuffled(n: usize, seed: u64) -> Vec<usize> {
    let mut state = seed | 1;
    let mut next = move || {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        state
    };
    let mut order: Vec<usize> = (0..n).collect();
    for i in (1..n).rev() {
        order.swap(i, next() as usize % (i + 1));
    }
    order
}
